name: termiboard-build
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build:
    name: termiboard-build
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test
    - name: Build
      run: go build
    - name: Result
      run: ./termiboard
